### ISSUE TITLE
Access to the Self-Aware Dataset

### ISSUE THREAD

**Issue by PKUCSS** [yinzhangyue/SelfAware#1]
@yinzhangyue Dear authors, congratulations on your splendid work! I'd like to know when you will make the Self-Aware dataset public. Many peers and I are looking forward to doing more research based on the valuable benchmark.

**Comment by yinzhangyue** [comment]
Thanks for your attention and commendation on our work. SelfAware dataset will be made public later this week!

**Comment by yinzhangyue** [comment]
Thank you for your interest, the code and data have been uploaded.
