### ISSUE TITLE
Where to put API-Key？

### ISSUE THREAD

**Issue by shizhengLi** [yinzhangyue/SelfAware#3]
Dear authors, thanks for the splendid work. I, now, reproduce your work, while encountering a problem-- where to put API-Key?

I just run the code like this with my own openai API key,

`python run_model.py --input-form Direct --model-name text-davinci-003 --API-Key xxx`

But the code didn't generate any output.

Hope that you can give me some advice. Thanks in advance for any help you can give.

**Comment by yinzhangyue** [comment]
Hello,

Thank you for your kind words and for trying out our work!

To address your concern:

1. Please ensure that your OpenAI account is active.
2. After running the program, do you see the `trange` progress bar? This would indicate that the code is actively processing.
3. Were there any error messages that appeared when you ran the code? If so, please share them with us.
4. Ensure that the code and any required data files are located in the same directory when executing the script.

Please provide this information so we can assist you further. Thanks for reaching out!

Best regards~

**Comment by shizhengLi** [comment]
Hello, when adding an API key and running the code, I got this:

> openai.error.RateLimitError: Rate limit reached for text-davinci-003 in organization org on requests per min. Limit: 3 / min. Please try again in 20s. Visit https://platform.openai.com/account/rate-limits to learn more. You can increase your rate limit by adding a payment method to your account at https://platform.openai.com/account/billing.

How can I fix this in China mainland? Would u mind adding my WeChat account  for details which is 15216727572?
